### ISSUE TITLE
借个地方反馈unlock cn gms模块的事

### ISSUE THREAD

**Issue by LennoC** [fei-ke/unlock-cn-gms#1]
你好，抱歉。因为unlock_cn_gms模块没开启issues，只能到这里来说一下了。
不知道你是用的什么手机，现在小米手机miui11，基于AndroidQ的版本，我去system/etc/permissions里找了下并没有services.cn.google.xml文件了，甚至连名字类似的跟cn或者google配置有关的没了。
这导致play商店一直请求services.googleapis.cn，而不是请求com域名。
刚好我用的机场，机场主在服务端屏蔽了所有国内域名包括cn以及国内IP，这导致就是哪怕设为走代理也会因为cn域名被block。。于是我还是不能用Play服务。
在国内用个安卓好难，想在安卓上用google也真难。实在搜不到新文章讲这件事的，只好请求帮助了。
我的手机：小米MIX3，系统MIUI11 开发版10.31，基于AndroidQ.
感谢作者，若需要我协助的请联系我。

**Comment by HellAction** [comment]
让你打开的不的模块,是你系统根目录下的/product/etc/permissions/,安卓10和11的services.cn.google.xml现在已经放在这里面了,一般ROM即使Root后也不允许修改product分区,官改MIUI可以尝试下.

**Comment by SsparKluo** [comment]
> 让你打开的不是模块,是你系统根目录下的/product/etc/permissions/,安卓10和11的services.cn.google.xml现在已经放在这里面了,一般ROM即使Root后也不允许修改product分区,官改MIUI可以尝试下.

所以现在是没办法了吗，如果不用官改的话

**Comment by SpeedPartner** [comment]
> > 让你打开的不是模块,是你系统根目录下的/product/etc/permissions/,安卓10和11的services.cn.google.xml现在已经放在这里面了,一般ROM即使Root后也不允许修改product分区,官改MIUI可以尝试下.
> 
> 所以现在是没办法了吗，如果不用官改的话

也可以,用magisk模块就行,模块里把这个xml替换为空文件.

**Comment by fei-ke** [comment]
https://github.com/fei-ke/unlock-cn-gms/releases/tag/v3
