### ISSUE TITLE
This zip is not a Magisk Module!

### ISSUE THREAD

**Issue by holibert** [fei-ke/unlock-cn-gms#2]
Magisk版本 20.3
Magisk Mannager版本 7.5.1(267)

已安装Riru - Location Report Enabler v9.3

**Comment by holibert** [comment]
我从github上直接download zip，然后再Mgisk Manager上打开就显示这个zip不是Magist Module

**Comment by fei-ke** [comment]
在 release 页面下载：
https://github.com/fei-ke/unlock-cn-gms/releases
