### ISSUE TITLE
android10目录变了，不能用了。

### ISSUE THREAD

**Issue by monkey-sking** [fei-ke/unlock-cn-gms#3]
改了目标目录下，web上的google play仍然没有设备

时间轴一直在记录，但地图里面没有时间轴入口，只有通过网页查看

**Comment by HellAction** [comment]
安卓10和11,换到/product/etc/permissions下面了,大部分ROM默认不允许修改该分区

**Comment by SugarRuy** [comment]
> 安卓10和11,换到/product/etc/permissions下面了,大部分ROM默认不允许修改该分区

多谢指导，unlock /system以后用同名空文件代替这个xml文件，成功打开了。型号是小米9 Android 10。

**Comment by leeaash** [comment]
Android 12 下/product/etc/permissions也没有这个文件了，需改成哪个路径或配置文件修改？

**Comment by SpeedPartner** [comment]
> Android 12 下/product/etc/permissions也没有这个文件了，需改成哪个路径或配置文件修改？

还没更新安卓12,但是我解包看了下,位置没变啊

**Comment by leeaash** [comment]
> 

我的是Oneplus 10 Pro ColorOS12, 可能权限控制不用这个文件。
一加的ColorOS，支持GMS，但是无法开启谷歌位置记录和打开语音唤醒Ok Google，不支持有无解决办法。

**Comment by SpeedPartner** [comment]
> > 
> 
> 我的是Oneplus 10 Pro ColorOS12, 可能权限控制不用这个文件。 一加的ColorOS，支持GMS，但是无法开启谷歌位置记录和打开语音唤醒Ok Google，不支持有无解决办法。

你应该还需要用到修改手机卡地区代码来欺骗GMS为非国内地区的"Location Report Enabler"的Magisk或者Xposed模块.

**Comment by leeaash** [comment]
> > 我的是Oneplus 10 Pro ColorOS12, 可能权限控制不用这个文件。 一加的ColorOS，支持GMS，但是无法开启谷歌位置记录和打开语音唤醒Ok Google，不支持有无解决办法。
> 
> 你应该还需要用到修改手机SIM地区代码来欺骗GMS为非国内地区的"Location Report Enabler"的Magisk或者Xposed模块.

Location Report Enabler 装了只能解决maps里打开timeline的问题，但是无法开启手机的“位置记录”功能

**Comment by fei-ke** [comment]
https://github.com/fei-ke/unlock-cn-gms/releases/tag/v3
