### ISSUE TITLE
MIUI 14 中文件更名为 cn.google.services.xml

### ISSUE THREAD

**Issue by tehcneko** [fei-ke/unlock-cn-gms#5]

**Comment by wenliu0706** [comment]
@tehcneko 
这个问题我也遇到了我的解决方式是
打开Root档案管理器编辑以下档案
`Root/data/adb/modules/com.fei_ke.unlockcngms/post-fs-data.sh`
进去后会看到里面有许多
`etc/permissions/services.cn.google.xml`
把里面的所有的`services.cn.google.xml`
替换成`cn.google.services.xml`
然后重启模块就恢复正常运作了

**Comment by Benjamin23333** [comment]
+1，我最近发现下载不了play store的app了，看了下文件目录发现文件名字改了，模块不起作用了

**Comment by Benjamin23333** [comment]
最近一个pr已经解决了，详见https://github.com/fei-ke/unlock-cn-gms/commit/d725b21edf9eb997a5245e4c3b9d915a6f970de3
只是还没生成只要把releases，只要把https://github.com/fei-ke/unlock-cn-gms/blob/master/post-fs-data.sh这个文件替换模块里的同名文件再刷入修改的模块就可以了

**Comment by fei-ke** [comment]
已发布适配 MIUI 14 的版本，action 中也增加了最新的打包
